Added Upload feature / Added more SQL Insert and update method to mak…
durlabhjain/dframework-node pull request #1
Opened 2021-11-03 11:17 UTC by PradeepKumar100791

…e easy requests

2021-12-07 14:01 UTC, durlabhjain requested changes

2021-12-07 14:01 UTC, durlabhjain commented on lib/util.js
> +    jsonToFormData: function (data) {
We can use have buildFormData or jsonToFormData with signature:

buildFormData: function(data, formData = new FormData(), parentKey)

2021-12-09 12:08 UTC, PradeepKumar100791 commented on lib/index.js
> +            result = await client.post(url, { form: params, body });
we have done this to upload file - we only send body in that case

2021-12-09 13:55 UTC, PradeepKumar100791 commented on lib/util.js
> +    jsonToFormData: function (data) {
Done

2022-01-07 13:06 UTC, durlabhjain commented
Rejected as most changes are now in the main branch. Let me know if we still need it.

2022-01-07 13:06 UTC, closed without merging