Enhance Error Email Specificity with User, Host, and IP Details
durlabhjain/dframework-node pull request #52
Opened 2024-08-21 07:26 UTC by Hari-Narayan-dev

2024-08-22 12:58 UTC, durlabhjain requested changes

2024-08-22 12:58 UTC, durlabhjain commented on lib/pino-http-send.mjs
> +                    Form: JSON.stringify(params || ''),
Are we sure we are using JSON.stringify from C# or are we creating a key value pair separated by new line?

Same goes with QueryString

2024-08-22 12:58 UTC, durlabhjain commented on lib/pino-http-send.mjs
> +                    AbsoluteUrl: `${req.serverUrl}internal-reporting${req.url}`
Why are we hard coding internal-reporting inframework?

AbsoluteleUrl and RawUrl - check the differences and use that logic

May be we just need 1

2024-08-22 13:23 UTC, Hari-Narayan-dev commented on lib/pino-http-send.mjs
> +                    Form: JSON.stringify(params || ''),
JSON.stringify is removed and sending the urlsearchparams as checked in C# we are sending the urlsearchparams

2024-08-22 13:25 UTC, Hari-Narayan-dev commented on lib/pino-http-send.mjs
> +                    AbsoluteUrl: `${req.serverUrl}internal-reporting${req.url}`
removed the hard coded internal-reporting in framework and checked we are getting raw url and absolute url both from c#

2024-08-23 16:59 UTC, durlabhjain approved these changes

2024-08-23 17:00 UTC, merged